# Generated by Django 6.0.2 on 2026-02-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='https://www.flaticon.es/iconos-gratis/', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portfolio.attribution'),
        ),
        migrations.AddField(
            model_name='technology',
            name='attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portfolio.attribution'),
        ),
    ]
