# Generated by Django 6.0.2 on 2026-02-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0002_attribution_skill_attribution_technology_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='attribution',
            field=models.URLField(blank=True, default='https://www.flaticon.es/iconos-gratis/', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='attribution',
            field=models.URLField(blank=True, default='https://www.flaticon.es/iconos-gratis/', null=True),
        ),
        migrations.DeleteModel(
            name='Attribution',
        ),
    ]
