# Generated by Django 6.0.2 on 2026-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0003_alter_technology_attribution_alter_skill_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default='https://www.flaticon.es/iconos-gratis/', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='attribution',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='attribution',
        ),
    ]
