# Generated by Django 6.0.2 on 2026-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0004_attribution_remove_skill_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('social_media', models.ManyToManyField(related_name='profiles', to='admin_portfolio.socialmedia')),
            ],
        ),
    ]
